#! /bin/sh
# /etc/init.d/piControl
#
NAME=piControl
APP=/opt/piControl/app.js
forever=forever

case "$1" in
  start)
	echo "Starting $NAME"
	$forever start $APP
    ;;
  stop)
	echo "Stopping script $NAME"
	$forever stop $APP
    ;;
  *)
    echo "Usage: /etc/init.d/pictlnode {start|stop}"
    exit 1
    ;;
esac

exit 0