#! /bin/sh
# /etc/init.d/piControl
#

### BEGIN INIT INFO
# Provides: piControl
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Run node pi control on boot
# Description:
### END INIT INFO

NAME=piControl
APP=/opt/piControl/app.js
forever=/usr/local/bin/forever
export PATH=$PATH:/usr/local/bin/

case "$1" in
  start)
	echo "Starting $NAME"
	$forever start $APP
    ;;
  stop)
	echo "Stopping script $NAME"
	$forever stop $APP
    ;;
  list)
	echo "List"
	$forever list
    ;;
  *)
    echo "Usage: /etc/init.d/pictlnode {start|stop|list}"
    exit 1
    ;;
esac

exit 0